### ISSUE TITLE
Subgroups are leaving HH

### ISSUE THREAD

**Issue by nsgomez** [HackathonHackers/groups#36]
HH Book Club --> Hackers - Book Club
HH Data Hackers --> Data Hackers
HH Freelance --> Freelance Hackers
HH Homework --> Hacker Homework
HH Information Security --> Information Security
HH Music --> Hack - Music

HH Ruby --> Ruby Hackers

HH Canada --> Canadian Hackers Eh?
HH California --> Cali Hackers
HH Midwest --> Midwest Hackers

HH Hacker Problems --> Hacker Problems
Real Singles of HH --> Sovereign State of Real Singles

**Comment by megan-curiosity** [comment]
HH Overheard/Overseen at Hackathons -> Overheard/Overseen at Hackathons

**Comment by rhallie15** [comment]
Can you submit a pull request for the changes?

**Comment by rpbeltran** [comment]
Would it be worthwhile to make a new category on the bottom like "Began as HH, now independent" and include the links to these groups there instead of completely removing them? I say this because a lot of people probably don't care if they are technically HH, and are just looking for groups targeted to their interests, and these groups can still serve that purpose. For example, I joined HH λ to learn more about functional programming, and now they they are not affiliated, others might have a harder time finding them if they are removed from lists like this.

**Comment by nsgomez** [comment]
I opted to remove the groups because I'm under the impression that this list only covers groups that are officially HH subgroups and voting in the admin elections. @arirawr has a fork that retains these groups:

https://github.com/arirawr/hackergroups
